[project]
name = "yggdrasil-engine"
version = "2.0.0a1"
description = "Engine for evaluating Unleash feature flags"
authors = [{ name = "Simon Hornby", email = "liquidwicked64@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

[tool.maturin]
manifest-path = "../yggdrasil-pyo3/Cargo.toml"
module-name = "yggdrasil_engine.yggdrasil_native"
python-source = "."
exclude = [
    "yggdrasil_engine/**/__pycache__/**",
    "yggdrasil_engine/lib/**",
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
tox = "^4.0.0"
ruff = "^0.16.1"
basedpyright = "^1.39.9"

[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py38"

lint.select = [
    "E",   # pycodestyle, error
    "W",   # pycodestyle, warning
    "F",   # pyflakes
    "PL",  # pylint
    "YTT", # flake8-2020
    "I",   # isort
]
lint.ignore = ["E501", "PLR2004"]
lint.fixable = ["I"]

[tool.ruff.lint.pylint]
max-args = 25

[tool.basedpyright]
pythonVersion = "3.8"
include = ["yggdrasil_engine", "tests"]
