# automatically generated by the FlatBuffers compiler, do not modify

# namespace: messaging

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImpactMetricEntryUnion(object):
    NONE = 0
    ImpactMetricCounterEntry = 1
    ImpactMetricGaugeEntry = 2
    ImpactMetricHistogramEntry = 3


class PropertyEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropertyEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropertyEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropertyEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropertyEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropertyEntry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PropertyEntryStart(builder):
    builder.StartObject(2)

def PropertyEntryAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def PropertyEntryAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def PropertyEntryEnd(builder):
    return builder.EndObject()



class ContextMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContextMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContextMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ContextMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContextMessage
    def ToggleName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def Environment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def AppName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def CurrentTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def RemoteAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def RuntimeHostname(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContextMessage
    def Properties(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PropertyEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ContextMessage
    def PropertiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ContextMessage
    def PropertiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # ContextMessage
    def CustomStrategiesResults(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CustomStrategyResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ContextMessage
    def CustomStrategiesResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ContextMessage
    def CustomStrategiesResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def ContextMessageStart(builder):
    builder.StartObject(10)

def ContextMessageAddToggleName(builder, toggleName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(toggleName), 0)

def ContextMessageAddUserId(builder, userId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(userId), 0)

def ContextMessageAddSessionId(builder, sessionId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def ContextMessageAddEnvironment(builder, environment):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(environment), 0)

def ContextMessageAddAppName(builder, appName):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(appName), 0)

def ContextMessageAddCurrentTime(builder, currentTime):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(currentTime), 0)

def ContextMessageAddRemoteAddress(builder, remoteAddress):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(remoteAddress), 0)

def ContextMessageAddRuntimeHostname(builder, runtimeHostname):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(runtimeHostname), 0)

def ContextMessageAddProperties(builder, properties):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(properties), 0)

def ContextMessageStartPropertiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ContextMessageAddCustomStrategiesResults(builder, customStrategiesResults):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(customStrategiesResults), 0)

def ContextMessageStartCustomStrategiesResultsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ContextMessageEnd(builder):
    return builder.EndObject()



class CustomStrategyResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CustomStrategyResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCustomStrategyResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CustomStrategyResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CustomStrategyResult
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CustomStrategyResult
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CustomStrategyResultStart(builder):
    builder.StartObject(2)

def CustomStrategyResultAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def CustomStrategyResultAddValue(builder, value):
    builder.PrependBoolSlot(1, value, 0)

def CustomStrategyResultEnd(builder):
    return builder.EndObject()



class Response(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Response
    def ImpressionData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Response
    def HasEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Response
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ResponseStart(builder):
    builder.StartObject(4)

def ResponseAddEnabled(builder, enabled):
    builder.PrependBoolSlot(0, enabled, 0)

def ResponseAddImpressionData(builder, impressionData):
    builder.PrependBoolSlot(1, impressionData, 0)

def ResponseAddHasEnabled(builder, hasEnabled):
    builder.PrependBoolSlot(2, hasEnabled, 0)

def ResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def ResponseEnd(builder):
    return builder.EndObject()



class VoidResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoidResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoidResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VoidResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoidResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def VoidResponseStart(builder):
    builder.StartObject(1)

def VoidResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def VoidResponseEnd(builder):
    return builder.EndObject()



class Variant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Variant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Variant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Variant
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Variant
    def ImpressionData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Variant
    def FeatureEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Variant
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Variant
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VariantPayload()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Variant
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def VariantStart(builder):
    builder.StartObject(6)

def VariantAddEnabled(builder, enabled):
    builder.PrependBoolSlot(0, enabled, 0)

def VariantAddImpressionData(builder, impressionData):
    builder.PrependBoolSlot(1, impressionData, 0)

def VariantAddFeatureEnabled(builder, featureEnabled):
    builder.PrependBoolSlot(2, featureEnabled, 0)

def VariantAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def VariantAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def VariantAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def VariantEnd(builder):
    return builder.EndObject()



class VariantPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariantPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariantPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariantPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariantPayload
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VariantPayload
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def VariantPayloadStart(builder):
    builder.StartObject(2)

def VariantPayloadAddPayloadType(builder, payloadType):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(payloadType), 0)

def VariantPayloadAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def VariantPayloadEnd(builder):
    return builder.EndObject()



class VariantEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VariantEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVariantEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VariantEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VariantEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VariantEntry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def VariantEntryStart(builder):
    builder.StartObject(2)

def VariantEntryAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def VariantEntryAddValue(builder, value):
    builder.PrependUint32Slot(1, value, 0)

def VariantEntryEnd(builder):
    return builder.EndObject()



class ToggleStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ToggleStats()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsToggleStats(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ToggleStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToggleStats
    def No(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ToggleStats
    def Yes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ToggleStats
    def Variants(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = VariantEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ToggleStats
    def VariantsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ToggleStats
    def VariantsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ToggleStatsStart(builder):
    builder.StartObject(3)

def ToggleStatsAddNo(builder, no):
    builder.PrependUint32Slot(0, no, 0)

def ToggleStatsAddYes(builder, yes):
    builder.PrependUint32Slot(1, yes, 0)

def ToggleStatsAddVariants(builder, variants):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(variants), 0)

def ToggleStatsStartVariantsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ToggleStatsEnd(builder):
    return builder.EndObject()



class CoreVersion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CoreVersion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCoreVersion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CoreVersion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CoreVersion
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CoreVersionStart(builder):
    builder.StartObject(1)

def CoreVersionAddVersion(builder, version):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)

def CoreVersionEnd(builder):
    return builder.EndObject()



class BuiltInStrategies(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BuiltInStrategies()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBuiltInStrategies(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BuiltInStrategies
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BuiltInStrategies
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # BuiltInStrategies
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BuiltInStrategies
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BuiltInStrategiesStart(builder):
    builder.StartObject(1)

def BuiltInStrategiesAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def BuiltInStrategiesStartValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def BuiltInStrategiesEnd(builder):
    return builder.EndObject()



class ToggleEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ToggleEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsToggleEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ToggleEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToggleEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToggleEntry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ToggleStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ToggleEntryStart(builder):
    builder.StartObject(2)

def ToggleEntryAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def ToggleEntryAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def ToggleEntryEnd(builder):
    return builder.EndObject()



class HistogramSampleBucketStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HistogramSampleBucketStats()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHistogramSampleBucketStats(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HistogramSampleBucketStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HistogramSampleBucketStats
    def Le(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # HistogramSampleBucketStats
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def HistogramSampleBucketStatsStart(builder):
    builder.StartObject(2)

def HistogramSampleBucketStatsAddLe(builder, le):
    builder.PrependFloat64Slot(0, le, 0.0)

def HistogramSampleBucketStatsAddCount(builder, count):
    builder.PrependInt64Slot(1, count, 0)

def HistogramSampleBucketStatsEnd(builder):
    return builder.EndObject()



class SampleLabelEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SampleLabelEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSampleLabelEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SampleLabelEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SampleLabelEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SampleLabelEntry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SampleLabelEntryStart(builder):
    builder.StartObject(2)

def SampleLabelEntryAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def SampleLabelEntryAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def SampleLabelEntryEnd(builder):
    return builder.EndObject()



class ImpactMetricHistogramStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricHistogramStats()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricHistogramStats(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricHistogramStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricHistogramStats
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SampleLabelEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricHistogramStats
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricHistogramStats
    def LabelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ImpactMetricHistogramStats
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ImpactMetricHistogramStats
    def Sum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ImpactMetricHistogramStats
    def Buckets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = HistogramSampleBucketStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricHistogramStats
    def BucketsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricHistogramStats
    def BucketsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def ImpactMetricHistogramStatsStart(builder):
    builder.StartObject(4)

def ImpactMetricHistogramStatsAddLabels(builder, labels):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0)

def ImpactMetricHistogramStatsStartLabelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricHistogramStatsAddCount(builder, count):
    builder.PrependInt64Slot(1, count, 0)

def ImpactMetricHistogramStatsAddSum(builder, sum):
    builder.PrependFloat64Slot(2, sum, 0.0)

def ImpactMetricHistogramStatsAddBuckets(builder, buckets):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(buckets), 0)

def ImpactMetricHistogramStatsStartBucketsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricHistogramStatsEnd(builder):
    return builder.EndObject()



class ImpactMetricGaugeStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricGaugeStats()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricGaugeStats(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricGaugeStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricGaugeStats
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SampleLabelEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricGaugeStats
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricGaugeStats
    def LabelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ImpactMetricGaugeStats
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ImpactMetricGaugeStatsStart(builder):
    builder.StartObject(2)

def ImpactMetricGaugeStatsAddLabels(builder, labels):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0)

def ImpactMetricGaugeStatsStartLabelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricGaugeStatsAddValue(builder, value):
    builder.PrependFloat64Slot(1, value, 0.0)

def ImpactMetricGaugeStatsEnd(builder):
    return builder.EndObject()



class ImpactMetricCounterStats(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricCounterStats()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricCounterStats(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricCounterStats
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricCounterStats
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SampleLabelEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricCounterStats
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricCounterStats
    def LabelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ImpactMetricCounterStats
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ImpactMetricCounterStatsStart(builder):
    builder.StartObject(2)

def ImpactMetricCounterStatsAddLabels(builder, labels):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0)

def ImpactMetricCounterStatsStartLabelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricCounterStatsAddValue(builder, value):
    builder.PrependInt64Slot(1, value, 0)

def ImpactMetricCounterStatsEnd(builder):
    return builder.EndObject()



class ImpactMetricGaugeEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricGaugeEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricGaugeEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricGaugeEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricGaugeEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImpactMetricGaugeEntry
    def Help(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImpactMetricGaugeEntry
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ImpactMetricGaugeStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricGaugeEntry
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricGaugeEntry
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ImpactMetricGaugeEntryStart(builder):
    builder.StartObject(3)

def ImpactMetricGaugeEntryAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def ImpactMetricGaugeEntryAddHelp(builder, help):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(help), 0)

def ImpactMetricGaugeEntryAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def ImpactMetricGaugeEntryStartSamplesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricGaugeEntryEnd(builder):
    return builder.EndObject()



class ImpactMetricCounterEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricCounterEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricCounterEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricCounterEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricCounterEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImpactMetricCounterEntry
    def Help(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImpactMetricCounterEntry
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ImpactMetricCounterStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricCounterEntry
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricCounterEntry
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ImpactMetricCounterEntryStart(builder):
    builder.StartObject(3)

def ImpactMetricCounterEntryAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def ImpactMetricCounterEntryAddHelp(builder, help):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(help), 0)

def ImpactMetricCounterEntryAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def ImpactMetricCounterEntryStartSamplesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricCounterEntryEnd(builder):
    return builder.EndObject()



class ImpactMetricHistogramEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricHistogramEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricHistogramEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricHistogramEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricHistogramEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImpactMetricHistogramEntry
    def Help(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImpactMetricHistogramEntry
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ImpactMetricHistogramStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImpactMetricHistogramEntry
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ImpactMetricHistogramEntry
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ImpactMetricHistogramEntryStart(builder):
    builder.StartObject(3)

def ImpactMetricHistogramEntryAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def ImpactMetricHistogramEntryAddHelp(builder, help):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(help), 0)

def ImpactMetricHistogramEntryAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def ImpactMetricHistogramEntryStartSamplesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ImpactMetricHistogramEntryEnd(builder):
    return builder.EndObject()



class ImpactMetricEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImpactMetricEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImpactMetricEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImpactMetricEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImpactMetricEntry
    def EntryType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ImpactMetricEntry
    def Entry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ImpactMetricEntryStart(builder):
    builder.StartObject(2)

def ImpactMetricEntryAddEntryType(builder, entryType):
    builder.PrependUint8Slot(0, entryType, 0)

def ImpactMetricEntryAddEntry(builder, entry):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(entry), 0)

def ImpactMetricEntryEnd(builder):
    return builder.EndObject()



class MetricsResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MetricsResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMetricsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MetricsResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MetricsResponse
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MetricsResponse
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MetricsResponse
    def Toggles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ToggleEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetricsResponse
    def TogglesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetricsResponse
    def TogglesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MetricsResponse
    def ImpactMetrics(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ImpactMetricEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetricsResponse
    def ImpactMetricsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MetricsResponse
    def ImpactMetricsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def MetricsResponseStart(builder):
    builder.StartObject(4)

def MetricsResponseAddStart(builder, start):
    builder.PrependInt64Slot(0, start, 0)

def MetricsResponseAddStop(builder, stop):
    builder.PrependInt64Slot(1, stop, 0)

def MetricsResponseAddToggles(builder, toggles):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(toggles), 0)

def MetricsResponseStartTogglesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def MetricsResponseAddImpactMetrics(builder, impactMetrics):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(impactMetrics), 0)

def MetricsResponseStartImpactMetricsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def MetricsResponseEnd(builder):
    return builder.EndObject()



class TakeStateResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TakeStateResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTakeStateResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TakeStateResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TakeStateResponse
    def Features(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = StrategyFeature()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TakeStateResponse
    def FeaturesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TakeStateResponse
    def FeaturesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TakeStateResponse
    def Warnings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TakeStateResponse
    def WarningsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TakeStateResponse
    def WarningsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # TakeStateResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TakeStateResponseStart(builder):
    builder.StartObject(3)

def TakeStateResponseAddFeatures(builder, features):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(features), 0)

def TakeStateResponseStartFeaturesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def TakeStateResponseAddWarnings(builder, warnings):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(warnings), 0)

def TakeStateResponseStartWarningsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def TakeStateResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def TakeStateResponseEnd(builder):
    return builder.EndObject()



class StrategyFeature(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StrategyFeature()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStrategyFeature(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StrategyFeature
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StrategyFeature
    def FeatureName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StrategyFeature
    def Strategies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = StrategyDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StrategyFeature
    def StrategiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StrategyFeature
    def StrategiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def StrategyFeatureStart(builder):
    builder.StartObject(2)

def StrategyFeatureAddFeatureName(builder, featureName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(featureName), 0)

def StrategyFeatureAddStrategies(builder, strategies):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(strategies), 0)

def StrategyFeatureStartStrategiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StrategyFeatureEnd(builder):
    return builder.EndObject()



class StrategyDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StrategyDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStrategyDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StrategyDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StrategyDefinition
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StrategyDefinition
    def Parameters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = StrategyParameter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StrategyDefinition
    def ParametersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StrategyDefinition
    def ParametersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def StrategyDefinitionStart(builder):
    builder.StartObject(2)

def StrategyDefinitionAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def StrategyDefinitionAddParameters(builder, parameters):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(parameters), 0)

def StrategyDefinitionStartParametersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StrategyDefinitionEnd(builder):
    return builder.EndObject()



class StrategyParameter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StrategyParameter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStrategyParameter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StrategyParameter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StrategyParameter
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StrategyParameter
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StrategyParameterStart(builder):
    builder.StartObject(2)

def StrategyParameterAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def StrategyParameterAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def StrategyParameterEnd(builder):
    return builder.EndObject()



class FeatureDef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeatureDef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFeatureDef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FeatureDef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FeatureDef
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FeatureDef
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FeatureDef
    def Project(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FeatureDef
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def FeatureDefStart(builder):
    builder.StartObject(4)

def FeatureDefAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def FeatureDefAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def FeatureDefAddProject(builder, project):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(project), 0)

def FeatureDefAddEnabled(builder, enabled):
    builder.PrependBoolSlot(3, enabled, 0)

def FeatureDefEnd(builder):
    return builder.EndObject()



class FeatureDefs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeatureDefs()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFeatureDefs(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FeatureDefs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FeatureDefs
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FeatureDef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeatureDefs
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FeatureDefs
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FeatureDefsStart(builder):
    builder.StartObject(1)

def FeatureDefsAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def FeatureDefsStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def FeatureDefsEnd(builder):
    return builder.EndObject()



class DefineCounter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DefineCounter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDefineCounter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DefineCounter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DefineCounter
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DefineCounter
    def Help(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DefineCounterStart(builder):
    builder.StartObject(2)

def DefineCounterAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def DefineCounterAddHelp(builder, help):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(help), 0)

def DefineCounterEnd(builder):
    return builder.EndObject()



class IncCounter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IncCounter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIncCounter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IncCounter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IncCounter
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IncCounter
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # IncCounter
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SampleLabelEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IncCounter
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IncCounter
    def LabelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def IncCounterStart(builder):
    builder.StartObject(3)

def IncCounterAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def IncCounterAddValue(builder, value):
    builder.PrependInt64Slot(1, value, 0)

def IncCounterAddLabels(builder, labels):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0)

def IncCounterStartLabelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def IncCounterEnd(builder):
    return builder.EndObject()



class DefineGauge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DefineGauge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDefineGauge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DefineGauge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DefineGauge
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DefineGauge
    def Help(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DefineGaugeStart(builder):
    builder.StartObject(2)

def DefineGaugeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def DefineGaugeAddHelp(builder, help):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(help), 0)

def DefineGaugeEnd(builder):
    return builder.EndObject()



class SetGauge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetGauge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetGauge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetGauge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetGauge
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetGauge
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SetGauge
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SampleLabelEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SetGauge
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SetGauge
    def LabelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SetGaugeStart(builder):
    builder.StartObject(3)

def SetGaugeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def SetGaugeAddValue(builder, value):
    builder.PrependFloat64Slot(1, value, 0.0)

def SetGaugeAddLabels(builder, labels):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0)

def SetGaugeStartLabelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SetGaugeEnd(builder):
    return builder.EndObject()



class DefineHistogram(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DefineHistogram()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDefineHistogram(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DefineHistogram
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DefineHistogram
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DefineHistogram
    def Help(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DefineHistogram
    def Buckets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # DefineHistogram
    def BucketsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # DefineHistogram
    def BucketsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DefineHistogram
    def BucketsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def DefineHistogramStart(builder):
    builder.StartObject(3)

def DefineHistogramAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def DefineHistogramAddHelp(builder, help):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(help), 0)

def DefineHistogramAddBuckets(builder, buckets):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(buckets), 0)

def DefineHistogramStartBucketsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def DefineHistogramEnd(builder):
    return builder.EndObject()



class ObserveHistogram(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObserveHistogram()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObserveHistogram(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ObserveHistogram
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObserveHistogram
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ObserveHistogram
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ObserveHistogram
    def Labels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = SampleLabelEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObserveHistogram
    def LabelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ObserveHistogram
    def LabelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ObserveHistogramStart(builder):
    builder.StartObject(3)

def ObserveHistogramAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def ObserveHistogramAddValue(builder, value):
    builder.PrependFloat64Slot(1, value, 0.0)

def ObserveHistogramAddLabels(builder, labels):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0)

def ObserveHistogramStartLabelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ObserveHistogramEnd(builder):
    return builder.EndObject()



class CollectMetricsResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CollectMetricsResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCollectMetricsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CollectMetricsResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CollectMetricsResponse
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CollectMetricsResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CollectMetricsResponseStart(builder):
    builder.StartObject(2)

def CollectMetricsResponseAddResponse(builder, response):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)

def CollectMetricsResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def CollectMetricsResponseEnd(builder):
    return builder.EndObject()



