// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CollectMetricsResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CollectMetricsResponse GetRootAsCollectMetricsResponse(ByteBuffer _bb) { return GetRootAsCollectMetricsResponse(_bb, new CollectMetricsResponse()); }
  public static CollectMetricsResponse GetRootAsCollectMetricsResponse(ByteBuffer _bb, CollectMetricsResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CollectMetricsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Response { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResponseBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetResponseBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetResponseArray() { return __p.__vector_as_array<byte>(4); }
  public string Error { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<yggdrasil.messaging.CollectMetricsResponse> CreateCollectMetricsResponse(FlatBufferBuilder builder,
      StringOffset responseOffset = default(StringOffset),
      StringOffset errorOffset = default(StringOffset)) {
    builder.StartTable(2);
    CollectMetricsResponse.AddError(builder, errorOffset);
    CollectMetricsResponse.AddResponse(builder, responseOffset);
    return CollectMetricsResponse.EndCollectMetricsResponse(builder);
  }

  public static void StartCollectMetricsResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddResponse(FlatBufferBuilder builder, StringOffset responseOffset) { builder.AddOffset(0, responseOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(1, errorOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.CollectMetricsResponse> EndCollectMetricsResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.CollectMetricsResponse>(o);
  }
}


static public class CollectMetricsResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Response*/, false)
      && verifier.VerifyString(tablePos, 6 /*Error*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
