// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ContextMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ContextMessage GetRootAsContextMessage(ByteBuffer _bb) { return GetRootAsContextMessage(_bb, new ContextMessage()); }
  public static ContextMessage GetRootAsContextMessage(ByteBuffer _bb, ContextMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ContextMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ToggleName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetToggleNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetToggleNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetToggleNameArray() { return __p.__vector_as_array<byte>(4); }
  public string UserId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUserIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUserIdArray() { return __p.__vector_as_array<byte>(6); }
  public string SessionId { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSessionIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetSessionIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetSessionIdArray() { return __p.__vector_as_array<byte>(8); }
  public string Environment { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEnvironmentBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetEnvironmentBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetEnvironmentArray() { return __p.__vector_as_array<byte>(10); }
  public string AppName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAppNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetAppNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetAppNameArray() { return __p.__vector_as_array<byte>(12); }
  public string CurrentTime { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCurrentTimeBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetCurrentTimeBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetCurrentTimeArray() { return __p.__vector_as_array<byte>(14); }
  public string RemoteAddress { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRemoteAddressBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetRemoteAddressBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetRemoteAddressArray() { return __p.__vector_as_array<byte>(16); }
  public string RuntimeHostname { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRuntimeHostnameBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetRuntimeHostnameBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetRuntimeHostnameArray() { return __p.__vector_as_array<byte>(18); }
  public yggdrasil.messaging.PropertyEntry? Properties(int j) { int o = __p.__offset(20); return o != 0 ? (yggdrasil.messaging.PropertyEntry?)(new yggdrasil.messaging.PropertyEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PropertiesLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
  public yggdrasil.messaging.PropertyEntry? PropertiesByKey(string key) { int o = __p.__offset(20); return o != 0 ? yggdrasil.messaging.PropertyEntry.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public yggdrasil.messaging.CustomStrategyResult? CustomStrategiesResults(int j) { int o = __p.__offset(22); return o != 0 ? (yggdrasil.messaging.CustomStrategyResult?)(new yggdrasil.messaging.CustomStrategyResult()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CustomStrategiesResultsLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
  public yggdrasil.messaging.CustomStrategyResult? CustomStrategiesResultsByKey(string key) { int o = __p.__offset(22); return o != 0 ? yggdrasil.messaging.CustomStrategyResult.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<yggdrasil.messaging.ContextMessage> CreateContextMessage(FlatBufferBuilder builder,
      StringOffset toggle_nameOffset = default(StringOffset),
      StringOffset user_idOffset = default(StringOffset),
      StringOffset session_idOffset = default(StringOffset),
      StringOffset environmentOffset = default(StringOffset),
      StringOffset app_nameOffset = default(StringOffset),
      StringOffset current_timeOffset = default(StringOffset),
      StringOffset remote_addressOffset = default(StringOffset),
      StringOffset runtime_hostnameOffset = default(StringOffset),
      VectorOffset propertiesOffset = default(VectorOffset),
      VectorOffset custom_strategies_resultsOffset = default(VectorOffset)) {
    builder.StartTable(10);
    ContextMessage.AddCustomStrategiesResults(builder, custom_strategies_resultsOffset);
    ContextMessage.AddProperties(builder, propertiesOffset);
    ContextMessage.AddRuntimeHostname(builder, runtime_hostnameOffset);
    ContextMessage.AddRemoteAddress(builder, remote_addressOffset);
    ContextMessage.AddCurrentTime(builder, current_timeOffset);
    ContextMessage.AddAppName(builder, app_nameOffset);
    ContextMessage.AddEnvironment(builder, environmentOffset);
    ContextMessage.AddSessionId(builder, session_idOffset);
    ContextMessage.AddUserId(builder, user_idOffset);
    ContextMessage.AddToggleName(builder, toggle_nameOffset);
    return ContextMessage.EndContextMessage(builder);
  }

  public static void StartContextMessage(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddToggleName(FlatBufferBuilder builder, StringOffset toggleNameOffset) { builder.AddOffset(0, toggleNameOffset.Value, 0); }
  public static void AddUserId(FlatBufferBuilder builder, StringOffset userIdOffset) { builder.AddOffset(1, userIdOffset.Value, 0); }
  public static void AddSessionId(FlatBufferBuilder builder, StringOffset sessionIdOffset) { builder.AddOffset(2, sessionIdOffset.Value, 0); }
  public static void AddEnvironment(FlatBufferBuilder builder, StringOffset environmentOffset) { builder.AddOffset(3, environmentOffset.Value, 0); }
  public static void AddAppName(FlatBufferBuilder builder, StringOffset appNameOffset) { builder.AddOffset(4, appNameOffset.Value, 0); }
  public static void AddCurrentTime(FlatBufferBuilder builder, StringOffset currentTimeOffset) { builder.AddOffset(5, currentTimeOffset.Value, 0); }
  public static void AddRemoteAddress(FlatBufferBuilder builder, StringOffset remoteAddressOffset) { builder.AddOffset(6, remoteAddressOffset.Value, 0); }
  public static void AddRuntimeHostname(FlatBufferBuilder builder, StringOffset runtimeHostnameOffset) { builder.AddOffset(7, runtimeHostnameOffset.Value, 0); }
  public static void AddProperties(FlatBufferBuilder builder, VectorOffset propertiesOffset) { builder.AddOffset(8, propertiesOffset.Value, 0); }
  public static VectorOffset CreatePropertiesVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.PropertyEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.PropertyEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.PropertyEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.PropertyEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddCustomStrategiesResults(FlatBufferBuilder builder, VectorOffset customStrategiesResultsOffset) { builder.AddOffset(9, customStrategiesResultsOffset.Value, 0); }
  public static VectorOffset CreateCustomStrategiesResultsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.CustomStrategyResult>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCustomStrategiesResultsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.CustomStrategyResult>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCustomStrategiesResultsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.CustomStrategyResult>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCustomStrategiesResultsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.CustomStrategyResult>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCustomStrategiesResultsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.ContextMessage> EndContextMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ContextMessage>(o);
  }
}


static public class ContextMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*ToggleName*/, false)
      && verifier.VerifyString(tablePos, 6 /*UserId*/, false)
      && verifier.VerifyString(tablePos, 8 /*SessionId*/, false)
      && verifier.VerifyString(tablePos, 10 /*Environment*/, false)
      && verifier.VerifyString(tablePos, 12 /*AppName*/, false)
      && verifier.VerifyString(tablePos, 14 /*CurrentTime*/, false)
      && verifier.VerifyString(tablePos, 16 /*RemoteAddress*/, false)
      && verifier.VerifyString(tablePos, 18 /*RuntimeHostname*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 20 /*Properties*/, yggdrasil.messaging.PropertyEntryVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 22 /*CustomStrategiesResults*/, yggdrasil.messaging.CustomStrategyResultVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
