// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CoreVersion : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CoreVersion GetRootAsCoreVersion(ByteBuffer _bb) { return GetRootAsCoreVersion(_bb, new CoreVersion()); }
  public static CoreVersion GetRootAsCoreVersion(ByteBuffer _bb, CoreVersion obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CoreVersion __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Version { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVersionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetVersionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetVersionArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<yggdrasil.messaging.CoreVersion> CreateCoreVersion(FlatBufferBuilder builder,
      StringOffset versionOffset = default(StringOffset)) {
    builder.StartTable(1);
    CoreVersion.AddVersion(builder, versionOffset);
    return CoreVersion.EndCoreVersion(builder);
  }

  public static void StartCoreVersion(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddVersion(FlatBufferBuilder builder, StringOffset versionOffset) { builder.AddOffset(0, versionOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.CoreVersion> EndCoreVersion(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.CoreVersion>(o);
  }
}


static public class CoreVersionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Version*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
