// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CustomStrategyResult : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CustomStrategyResult GetRootAsCustomStrategyResult(ByteBuffer _bb) { return GetRootAsCustomStrategyResult(_bb, new CustomStrategyResult()); }
  public static CustomStrategyResult GetRootAsCustomStrategyResult(ByteBuffer _bb, CustomStrategyResult obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CustomStrategyResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Key { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetKeyArray() { return __p.__vector_as_array<byte>(4); }
  public bool Value { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<yggdrasil.messaging.CustomStrategyResult> CreateCustomStrategyResult(FlatBufferBuilder builder,
      StringOffset keyOffset = default(StringOffset),
      bool value = false) {
    builder.StartTable(2);
    CustomStrategyResult.AddKey(builder, keyOffset);
    CustomStrategyResult.AddValue(builder, value);
    return CustomStrategyResult.EndCustomStrategyResult(builder);
  }

  public static void StartCustomStrategyResult(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, StringOffset keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(1, value, false); }
  public static Offset<yggdrasil.messaging.CustomStrategyResult> EndCustomStrategyResult(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // key
    return new Offset<yggdrasil.messaging.CustomStrategyResult>(o);
  }

  public static VectorOffset CreateSortedVectorOfCustomStrategyResult(FlatBufferBuilder builder, Offset<CustomStrategyResult>[] offsets) {
    Array.Sort(offsets,
      (Offset<CustomStrategyResult> o1, Offset<CustomStrategyResult> o2) =>
        new CustomStrategyResult().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).Key.CompareTo(new CustomStrategyResult().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).Key));
    return builder.CreateVectorOfTables(offsets);
  }

  public static CustomStrategyResult? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    CustomStrategyResult obj_ = new CustomStrategyResult();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.Key.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class CustomStrategyResultVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Key*/, true)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
