// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DefineCounter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DefineCounter GetRootAsDefineCounter(ByteBuffer _bb) { return GetRootAsDefineCounter(_bb, new DefineCounter()); }
  public static DefineCounter GetRootAsDefineCounter(ByteBuffer _bb, DefineCounter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DefineCounter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Help { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHelpBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetHelpBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetHelpArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<yggdrasil.messaging.DefineCounter> CreateDefineCounter(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset helpOffset = default(StringOffset)) {
    builder.StartTable(2);
    DefineCounter.AddHelp(builder, helpOffset);
    DefineCounter.AddName(builder, nameOffset);
    return DefineCounter.EndDefineCounter(builder);
  }

  public static void StartDefineCounter(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddHelp(FlatBufferBuilder builder, StringOffset helpOffset) { builder.AddOffset(1, helpOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.DefineCounter> EndDefineCounter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.DefineCounter>(o);
  }
}


static public class DefineCounterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyString(tablePos, 6 /*Help*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
