// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FeatureDefs : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FeatureDefs GetRootAsFeatureDefs(ByteBuffer _bb) { return GetRootAsFeatureDefs(_bb, new FeatureDefs()); }
  public static FeatureDefs GetRootAsFeatureDefs(ByteBuffer _bb, FeatureDefs obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FeatureDefs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public yggdrasil.messaging.FeatureDef? Items(int j) { int o = __p.__offset(4); return o != 0 ? (yggdrasil.messaging.FeatureDef?)(new yggdrasil.messaging.FeatureDef()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<yggdrasil.messaging.FeatureDefs> CreateFeatureDefs(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FeatureDefs.AddItems(builder, itemsOffset);
    return FeatureDefs.EndFeatureDefs(builder);
  }

  public static void StartFeatureDefs(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.FeatureDef>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.FeatureDef>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.FeatureDef>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.FeatureDef>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.FeatureDefs> EndFeatureDefs(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.FeatureDefs>(o);
  }
}


static public class FeatureDefsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Items*/, yggdrasil.messaging.FeatureDefVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
