// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FeatureDef : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FeatureDef GetRootAsFeatureDef(ByteBuffer _bb) { return GetRootAsFeatureDef(_bb, new FeatureDef()); }
  public static FeatureDef GetRootAsFeatureDef(ByteBuffer _bb, FeatureDef obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FeatureDef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Type { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTypeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTypeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTypeArray() { return __p.__vector_as_array<byte>(6); }
  public string Project { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProjectBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetProjectBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetProjectArray() { return __p.__vector_as_array<byte>(8); }
  public bool Enabled { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<yggdrasil.messaging.FeatureDef> CreateFeatureDef(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset typeOffset = default(StringOffset),
      StringOffset projectOffset = default(StringOffset),
      bool enabled = false) {
    builder.StartTable(4);
    FeatureDef.AddProject(builder, projectOffset);
    FeatureDef.AddType(builder, typeOffset);
    FeatureDef.AddName(builder, nameOffset);
    FeatureDef.AddEnabled(builder, enabled);
    return FeatureDef.EndFeatureDef(builder);
  }

  public static void StartFeatureDef(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddType(FlatBufferBuilder builder, StringOffset typeOffset) { builder.AddOffset(1, typeOffset.Value, 0); }
  public static void AddProject(FlatBufferBuilder builder, StringOffset projectOffset) { builder.AddOffset(2, projectOffset.Value, 0); }
  public static void AddEnabled(FlatBufferBuilder builder, bool enabled) { builder.AddBool(3, enabled, false); }
  public static Offset<yggdrasil.messaging.FeatureDef> EndFeatureDef(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.FeatureDef>(o);
  }
}


static public class FeatureDefVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyString(tablePos, 6 /*Type*/, false)
      && verifier.VerifyString(tablePos, 8 /*Project*/, false)
      && verifier.VerifyField(tablePos, 10 /*Enabled*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
