// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct HistogramSampleBucketStats : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static HistogramSampleBucketStats GetRootAsHistogramSampleBucketStats(ByteBuffer _bb) { return GetRootAsHistogramSampleBucketStats(_bb, new HistogramSampleBucketStats()); }
  public static HistogramSampleBucketStats GetRootAsHistogramSampleBucketStats(ByteBuffer _bb, HistogramSampleBucketStats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HistogramSampleBucketStats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Le { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public long Count { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<yggdrasil.messaging.HistogramSampleBucketStats> CreateHistogramSampleBucketStats(FlatBufferBuilder builder,
      double le = 0.0,
      long count = 0) {
    builder.StartTable(2);
    HistogramSampleBucketStats.AddCount(builder, count);
    HistogramSampleBucketStats.AddLe(builder, le);
    return HistogramSampleBucketStats.EndHistogramSampleBucketStats(builder);
  }

  public static void StartHistogramSampleBucketStats(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLe(FlatBufferBuilder builder, double le) { builder.AddDouble(0, le, 0.0); }
  public static void AddCount(FlatBufferBuilder builder, long count) { builder.AddLong(1, count, 0); }
  public static Offset<yggdrasil.messaging.HistogramSampleBucketStats> EndHistogramSampleBucketStats(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.HistogramSampleBucketStats>(o);
  }
}


static public class HistogramSampleBucketStatsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Le*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Count*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
