// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ImpactMetricGaugeStats : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ImpactMetricGaugeStats GetRootAsImpactMetricGaugeStats(ByteBuffer _bb) { return GetRootAsImpactMetricGaugeStats(_bb, new ImpactMetricGaugeStats()); }
  public static ImpactMetricGaugeStats GetRootAsImpactMetricGaugeStats(ByteBuffer _bb, ImpactMetricGaugeStats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ImpactMetricGaugeStats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public yggdrasil.messaging.SampleLabelEntry? Labels(int j) { int o = __p.__offset(4); return o != 0 ? (yggdrasil.messaging.SampleLabelEntry?)(new yggdrasil.messaging.SampleLabelEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LabelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public yggdrasil.messaging.SampleLabelEntry? LabelsByKey(string key) { int o = __p.__offset(4); return o != 0 ? yggdrasil.messaging.SampleLabelEntry.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public double Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<yggdrasil.messaging.ImpactMetricGaugeStats> CreateImpactMetricGaugeStats(FlatBufferBuilder builder,
      VectorOffset labelsOffset = default(VectorOffset),
      double value = 0.0) {
    builder.StartTable(2);
    ImpactMetricGaugeStats.AddValue(builder, value);
    ImpactMetricGaugeStats.AddLabels(builder, labelsOffset);
    return ImpactMetricGaugeStats.EndImpactMetricGaugeStats(builder);
  }

  public static void StartImpactMetricGaugeStats(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLabels(FlatBufferBuilder builder, VectorOffset labelsOffset) { builder.AddOffset(0, labelsOffset.Value, 0); }
  public static VectorOffset CreateLabelsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.SampleLabelEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.SampleLabelEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.SampleLabelEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.SampleLabelEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLabelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(1, value, 0.0); }
  public static Offset<yggdrasil.messaging.ImpactMetricGaugeStats> EndImpactMetricGaugeStats(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ImpactMetricGaugeStats>(o);
  }
}


static public class ImpactMetricGaugeStatsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Labels*/, yggdrasil.messaging.SampleLabelEntryVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 8 /*double*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
