// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ImpactMetricHistogramStats : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ImpactMetricHistogramStats GetRootAsImpactMetricHistogramStats(ByteBuffer _bb) { return GetRootAsImpactMetricHistogramStats(_bb, new ImpactMetricHistogramStats()); }
  public static ImpactMetricHistogramStats GetRootAsImpactMetricHistogramStats(ByteBuffer _bb, ImpactMetricHistogramStats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ImpactMetricHistogramStats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public yggdrasil.messaging.SampleLabelEntry? Labels(int j) { int o = __p.__offset(4); return o != 0 ? (yggdrasil.messaging.SampleLabelEntry?)(new yggdrasil.messaging.SampleLabelEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LabelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public yggdrasil.messaging.SampleLabelEntry? LabelsByKey(string key) { int o = __p.__offset(4); return o != 0 ? yggdrasil.messaging.SampleLabelEntry.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public long Count { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public double Sum { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public yggdrasil.messaging.HistogramSampleBucketStats? Buckets(int j) { int o = __p.__offset(10); return o != 0 ? (yggdrasil.messaging.HistogramSampleBucketStats?)(new yggdrasil.messaging.HistogramSampleBucketStats()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BucketsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<yggdrasil.messaging.ImpactMetricHistogramStats> CreateImpactMetricHistogramStats(FlatBufferBuilder builder,
      VectorOffset labelsOffset = default(VectorOffset),
      long count = 0,
      double sum = 0.0,
      VectorOffset bucketsOffset = default(VectorOffset)) {
    builder.StartTable(4);
    ImpactMetricHistogramStats.AddSum(builder, sum);
    ImpactMetricHistogramStats.AddCount(builder, count);
    ImpactMetricHistogramStats.AddBuckets(builder, bucketsOffset);
    ImpactMetricHistogramStats.AddLabels(builder, labelsOffset);
    return ImpactMetricHistogramStats.EndImpactMetricHistogramStats(builder);
  }

  public static void StartImpactMetricHistogramStats(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddLabels(FlatBufferBuilder builder, VectorOffset labelsOffset) { builder.AddOffset(0, labelsOffset.Value, 0); }
  public static VectorOffset CreateLabelsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.SampleLabelEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.SampleLabelEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.SampleLabelEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.SampleLabelEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLabelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddCount(FlatBufferBuilder builder, long count) { builder.AddLong(1, count, 0); }
  public static void AddSum(FlatBufferBuilder builder, double sum) { builder.AddDouble(2, sum, 0.0); }
  public static void AddBuckets(FlatBufferBuilder builder, VectorOffset bucketsOffset) { builder.AddOffset(3, bucketsOffset.Value, 0); }
  public static VectorOffset CreateBucketsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.HistogramSampleBucketStats>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBucketsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.HistogramSampleBucketStats>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBucketsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.HistogramSampleBucketStats>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBucketsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.HistogramSampleBucketStats>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBucketsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.ImpactMetricHistogramStats> EndImpactMetricHistogramStats(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ImpactMetricHistogramStats>(o);
  }
}


static public class ImpactMetricHistogramStatsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Labels*/, yggdrasil.messaging.SampleLabelEntryVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Count*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*Sum*/, 8 /*double*/, 8, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*Buckets*/, yggdrasil.messaging.HistogramSampleBucketStatsVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
