// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

public enum ImpactMetricEntryUnion : byte
{
  NONE = 0,
  ImpactMetricCounterEntry = 1,
  ImpactMetricGaugeEntry = 2,
  ImpactMetricHistogramEntry = 3,
};



static public class ImpactMetricEntryUnionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ImpactMetricEntryUnion)typeId)
    {
      case ImpactMetricEntryUnion.ImpactMetricCounterEntry:
        result = yggdrasil.messaging.ImpactMetricCounterEntryVerify.Verify(verifier, tablePos);
        break;
      case ImpactMetricEntryUnion.ImpactMetricGaugeEntry:
        result = yggdrasil.messaging.ImpactMetricGaugeEntryVerify.Verify(verifier, tablePos);
        break;
      case ImpactMetricEntryUnion.ImpactMetricHistogramEntry:
        result = yggdrasil.messaging.ImpactMetricHistogramEntryVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
