// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ImpactMetricResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ImpactMetricResponse GetRootAsImpactMetricResponse(ByteBuffer _bb) { return GetRootAsImpactMetricResponse(_bb, new ImpactMetricResponse()); }
  public static ImpactMetricResponse GetRootAsImpactMetricResponse(ByteBuffer _bb, ImpactMetricResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyImpactMetricResponse(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ImpactMetricResponseVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ImpactMetricResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Error { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<yggdrasil.messaging.ImpactMetricResponse> CreateImpactMetricResponse(FlatBufferBuilder builder,
      StringOffset errorOffset = default(StringOffset)) {
    builder.StartTable(1);
    ImpactMetricResponse.AddError(builder, errorOffset);
    return ImpactMetricResponse.EndImpactMetricResponse(builder);
  }

  public static void StartImpactMetricResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(0, errorOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.ImpactMetricResponse> EndImpactMetricResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ImpactMetricResponse>(o);
  }
  public static void FinishImpactMetricResponseBuffer(FlatBufferBuilder builder, Offset<yggdrasil.messaging.ImpactMetricResponse> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedImpactMetricResponseBuffer(FlatBufferBuilder builder, Offset<yggdrasil.messaging.ImpactMetricResponse> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ImpactMetricResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Error*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
