// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ImpactMetricEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ImpactMetricEntry GetRootAsImpactMetricEntry(ByteBuffer _bb) { return GetRootAsImpactMetricEntry(_bb, new ImpactMetricEntry()); }
  public static ImpactMetricEntry GetRootAsImpactMetricEntry(ByteBuffer _bb, ImpactMetricEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ImpactMetricEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public yggdrasil.messaging.ImpactMetricEntryUnion EntryType { get { int o = __p.__offset(4); return o != 0 ? (yggdrasil.messaging.ImpactMetricEntryUnion)__p.bb.Get(o + __p.bb_pos) : yggdrasil.messaging.ImpactMetricEntryUnion.NONE; } }
  public TTable? Entry<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public yggdrasil.messaging.ImpactMetricCounterEntry EntryAsImpactMetricCounterEntry() { return Entry<yggdrasil.messaging.ImpactMetricCounterEntry>().Value; }
  public yggdrasil.messaging.ImpactMetricGaugeEntry EntryAsImpactMetricGaugeEntry() { return Entry<yggdrasil.messaging.ImpactMetricGaugeEntry>().Value; }
  public yggdrasil.messaging.ImpactMetricHistogramEntry EntryAsImpactMetricHistogramEntry() { return Entry<yggdrasil.messaging.ImpactMetricHistogramEntry>().Value; }

  public static Offset<yggdrasil.messaging.ImpactMetricEntry> CreateImpactMetricEntry(FlatBufferBuilder builder,
      yggdrasil.messaging.ImpactMetricEntryUnion entry_type = yggdrasil.messaging.ImpactMetricEntryUnion.NONE,
      int entryOffset = 0) {
    builder.StartTable(2);
    ImpactMetricEntry.AddEntry(builder, entryOffset);
    ImpactMetricEntry.AddEntryType(builder, entry_type);
    return ImpactMetricEntry.EndImpactMetricEntry(builder);
  }

  public static void StartImpactMetricEntry(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEntryType(FlatBufferBuilder builder, yggdrasil.messaging.ImpactMetricEntryUnion entryType) { builder.AddByte(0, (byte)entryType, 0); }
  public static void AddEntry(FlatBufferBuilder builder, int entryOffset) { builder.AddOffset(1, entryOffset, 0); }
  public static Offset<yggdrasil.messaging.ImpactMetricEntry> EndImpactMetricEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ImpactMetricEntry>(o);
  }
}


static public class ImpactMetricEntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EntryType*/, 1 /*yggdrasil.messaging.ImpactMetricEntryUnion*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Entry*/, yggdrasil.messaging.ImpactMetricEntryUnionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
