// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ImpactMetricCounterEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ImpactMetricCounterEntry GetRootAsImpactMetricCounterEntry(ByteBuffer _bb) { return GetRootAsImpactMetricCounterEntry(_bb, new ImpactMetricCounterEntry()); }
  public static ImpactMetricCounterEntry GetRootAsImpactMetricCounterEntry(ByteBuffer _bb, ImpactMetricCounterEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ImpactMetricCounterEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Help { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHelpBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetHelpBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetHelpArray() { return __p.__vector_as_array<byte>(6); }
  public yggdrasil.messaging.ImpactMetricCounterStats? Samples(int j) { int o = __p.__offset(8); return o != 0 ? (yggdrasil.messaging.ImpactMetricCounterStats?)(new yggdrasil.messaging.ImpactMetricCounterStats()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SamplesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<yggdrasil.messaging.ImpactMetricCounterEntry> CreateImpactMetricCounterEntry(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset helpOffset = default(StringOffset),
      VectorOffset samplesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    ImpactMetricCounterEntry.AddSamples(builder, samplesOffset);
    ImpactMetricCounterEntry.AddHelp(builder, helpOffset);
    ImpactMetricCounterEntry.AddName(builder, nameOffset);
    return ImpactMetricCounterEntry.EndImpactMetricCounterEntry(builder);
  }

  public static void StartImpactMetricCounterEntry(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddHelp(FlatBufferBuilder builder, StringOffset helpOffset) { builder.AddOffset(1, helpOffset.Value, 0); }
  public static void AddSamples(FlatBufferBuilder builder, VectorOffset samplesOffset) { builder.AddOffset(2, samplesOffset.Value, 0); }
  public static VectorOffset CreateSamplesVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.ImpactMetricCounterStats>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSamplesVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.ImpactMetricCounterStats>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSamplesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.ImpactMetricCounterStats>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSamplesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.ImpactMetricCounterStats>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSamplesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.ImpactMetricCounterEntry> EndImpactMetricCounterEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ImpactMetricCounterEntry>(o);
  }
}


static public class ImpactMetricCounterEntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyString(tablePos, 6 /*Help*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Samples*/, yggdrasil.messaging.ImpactMetricCounterStatsVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
