// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Response : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Response GetRootAsResponse(ByteBuffer _bb) { return GetRootAsResponse(_bb, new Response()); }
  public static Response GetRootAsResponse(ByteBuffer _bb, Response obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Response __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Enabled { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool ImpressionData { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool HasEnabled { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Error { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<yggdrasil.messaging.Response> CreateResponse(FlatBufferBuilder builder,
      bool enabled = false,
      bool impression_data = false,
      bool has_enabled = false,
      StringOffset errorOffset = default(StringOffset)) {
    builder.StartTable(4);
    Response.AddError(builder, errorOffset);
    Response.AddHasEnabled(builder, has_enabled);
    Response.AddImpressionData(builder, impression_data);
    Response.AddEnabled(builder, enabled);
    return Response.EndResponse(builder);
  }

  public static void StartResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEnabled(FlatBufferBuilder builder, bool enabled) { builder.AddBool(0, enabled, false); }
  public static void AddImpressionData(FlatBufferBuilder builder, bool impressionData) { builder.AddBool(1, impressionData, false); }
  public static void AddHasEnabled(FlatBufferBuilder builder, bool hasEnabled) { builder.AddBool(2, hasEnabled, false); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(3, errorOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.Response> EndResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.Response>(o);
  }
}


static public class ResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Enabled*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*ImpressionData*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*HasEnabled*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 10 /*Error*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
