// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetGauge : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetGauge GetRootAsSetGauge(ByteBuffer _bb) { return GetRootAsSetGauge(_bb, new SetGauge()); }
  public static SetGauge GetRootAsSetGauge(ByteBuffer _bb, SetGauge obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetGauge __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public double Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public yggdrasil.messaging.SampleLabelEntry? Labels(int j) { int o = __p.__offset(8); return o != 0 ? (yggdrasil.messaging.SampleLabelEntry?)(new yggdrasil.messaging.SampleLabelEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LabelsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public yggdrasil.messaging.SampleLabelEntry? LabelsByKey(string key) { int o = __p.__offset(8); return o != 0 ? yggdrasil.messaging.SampleLabelEntry.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<yggdrasil.messaging.SetGauge> CreateSetGauge(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      double value = 0.0,
      VectorOffset labelsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    SetGauge.AddValue(builder, value);
    SetGauge.AddLabels(builder, labelsOffset);
    SetGauge.AddName(builder, nameOffset);
    return SetGauge.EndSetGauge(builder);
  }

  public static void StartSetGauge(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(1, value, 0.0); }
  public static void AddLabels(FlatBufferBuilder builder, VectorOffset labelsOffset) { builder.AddOffset(2, labelsOffset.Value, 0); }
  public static VectorOffset CreateLabelsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.SampleLabelEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.SampleLabelEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.SampleLabelEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLabelsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.SampleLabelEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLabelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.SetGauge> EndSetGauge(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.SetGauge>(o);
  }
}


static public class SetGaugeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 8 /*double*/, 8, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Labels*/, yggdrasil.messaging.SampleLabelEntryVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
