// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StrategyFeature : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static StrategyFeature GetRootAsStrategyFeature(ByteBuffer _bb) { return GetRootAsStrategyFeature(_bb, new StrategyFeature()); }
  public static StrategyFeature GetRootAsStrategyFeature(ByteBuffer _bb, StrategyFeature obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StrategyFeature __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string FeatureName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFeatureNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFeatureNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFeatureNameArray() { return __p.__vector_as_array<byte>(4); }
  public yggdrasil.messaging.StrategyDefinition? Strategies(int j) { int o = __p.__offset(6); return o != 0 ? (yggdrasil.messaging.StrategyDefinition?)(new yggdrasil.messaging.StrategyDefinition()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int StrategiesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<yggdrasil.messaging.StrategyFeature> CreateStrategyFeature(FlatBufferBuilder builder,
      StringOffset feature_nameOffset = default(StringOffset),
      VectorOffset strategiesOffset = default(VectorOffset)) {
    builder.StartTable(2);
    StrategyFeature.AddStrategies(builder, strategiesOffset);
    StrategyFeature.AddFeatureName(builder, feature_nameOffset);
    return StrategyFeature.EndStrategyFeature(builder);
  }

  public static void StartStrategyFeature(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddFeatureName(FlatBufferBuilder builder, StringOffset featureNameOffset) { builder.AddOffset(0, featureNameOffset.Value, 0); }
  public static void AddStrategies(FlatBufferBuilder builder, VectorOffset strategiesOffset) { builder.AddOffset(1, strategiesOffset.Value, 0); }
  public static VectorOffset CreateStrategiesVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.StrategyDefinition>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStrategiesVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.StrategyDefinition>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStrategiesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.StrategyDefinition>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStrategiesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.StrategyDefinition>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStrategiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.StrategyFeature> EndStrategyFeature(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.StrategyFeature>(o);
  }
}


static public class StrategyFeatureVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*FeatureName*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Strategies*/, yggdrasil.messaging.StrategyDefinitionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
