// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TakeStateResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static TakeStateResponse GetRootAsTakeStateResponse(ByteBuffer _bb) { return GetRootAsTakeStateResponse(_bb, new TakeStateResponse()); }
  public static TakeStateResponse GetRootAsTakeStateResponse(ByteBuffer _bb, TakeStateResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TakeStateResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public yggdrasil.messaging.StrategyFeature? Features(int j) { int o = __p.__offset(4); return o != 0 ? (yggdrasil.messaging.StrategyFeature?)(new yggdrasil.messaging.StrategyFeature()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FeaturesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string Warnings(int j) { int o = __p.__offset(6); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int WarningsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string Error { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<yggdrasil.messaging.TakeStateResponse> CreateTakeStateResponse(FlatBufferBuilder builder,
      VectorOffset featuresOffset = default(VectorOffset),
      VectorOffset warningsOffset = default(VectorOffset),
      StringOffset errorOffset = default(StringOffset)) {
    builder.StartTable(3);
    TakeStateResponse.AddError(builder, errorOffset);
    TakeStateResponse.AddWarnings(builder, warningsOffset);
    TakeStateResponse.AddFeatures(builder, featuresOffset);
    return TakeStateResponse.EndTakeStateResponse(builder);
  }

  public static void StartTakeStateResponse(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddFeatures(FlatBufferBuilder builder, VectorOffset featuresOffset) { builder.AddOffset(0, featuresOffset.Value, 0); }
  public static VectorOffset CreateFeaturesVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.StrategyFeature>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFeaturesVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.StrategyFeature>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFeaturesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.StrategyFeature>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFeaturesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.StrategyFeature>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFeaturesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWarnings(FlatBufferBuilder builder, VectorOffset warningsOffset) { builder.AddOffset(1, warningsOffset.Value, 0); }
  public static VectorOffset CreateWarningsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateWarningsVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWarningsVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateWarningsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartWarningsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(2, errorOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.TakeStateResponse> EndTakeStateResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.TakeStateResponse>(o);
  }
}


static public class TakeStateResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Features*/, yggdrasil.messaging.StrategyFeatureVerify.Verify, false)
      && verifier.VerifyVectorOfStrings(tablePos, 6 /*Warnings*/, false)
      && verifier.VerifyString(tablePos, 8 /*Error*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
