// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ToggleEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ToggleEntry GetRootAsToggleEntry(ByteBuffer _bb) { return GetRootAsToggleEntry(_bb, new ToggleEntry()); }
  public static ToggleEntry GetRootAsToggleEntry(ByteBuffer _bb, ToggleEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ToggleEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Key { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetKeyArray() { return __p.__vector_as_array<byte>(4); }
  public yggdrasil.messaging.ToggleStats? Value { get { int o = __p.__offset(6); return o != 0 ? (yggdrasil.messaging.ToggleStats?)(new yggdrasil.messaging.ToggleStats()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<yggdrasil.messaging.ToggleEntry> CreateToggleEntry(FlatBufferBuilder builder,
      StringOffset keyOffset = default(StringOffset),
      Offset<yggdrasil.messaging.ToggleStats> valueOffset = default(Offset<yggdrasil.messaging.ToggleStats>)) {
    builder.StartTable(2);
    ToggleEntry.AddValue(builder, valueOffset);
    ToggleEntry.AddKey(builder, keyOffset);
    return ToggleEntry.EndToggleEntry(builder);
  }

  public static void StartToggleEntry(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, StringOffset keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, Offset<yggdrasil.messaging.ToggleStats> valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.ToggleEntry> EndToggleEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ToggleEntry>(o);
  }
}


static public class ToggleEntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Key*/, false)
      && verifier.VerifyTable(tablePos, 6 /*Value*/, yggdrasil.messaging.ToggleStatsVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
