// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ToggleStats : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ToggleStats GetRootAsToggleStats(ByteBuffer _bb) { return GetRootAsToggleStats(_bb, new ToggleStats()); }
  public static ToggleStats GetRootAsToggleStats(ByteBuffer _bb, ToggleStats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ToggleStats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint No { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Yes { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public yggdrasil.messaging.VariantEntry? Variants(int j) { int o = __p.__offset(8); return o != 0 ? (yggdrasil.messaging.VariantEntry?)(new yggdrasil.messaging.VariantEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int VariantsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<yggdrasil.messaging.ToggleStats> CreateToggleStats(FlatBufferBuilder builder,
      uint no = 0,
      uint yes = 0,
      VectorOffset variantsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    ToggleStats.AddVariants(builder, variantsOffset);
    ToggleStats.AddYes(builder, yes);
    ToggleStats.AddNo(builder, no);
    return ToggleStats.EndToggleStats(builder);
  }

  public static void StartToggleStats(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddNo(FlatBufferBuilder builder, uint no) { builder.AddUint(0, no, 0); }
  public static void AddYes(FlatBufferBuilder builder, uint yes) { builder.AddUint(1, yes, 0); }
  public static void AddVariants(FlatBufferBuilder builder, VectorOffset variantsOffset) { builder.AddOffset(2, variantsOffset.Value, 0); }
  public static VectorOffset CreateVariantsVector(FlatBufferBuilder builder, Offset<yggdrasil.messaging.VariantEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateVariantsVectorBlock(FlatBufferBuilder builder, Offset<yggdrasil.messaging.VariantEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVariantsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<yggdrasil.messaging.VariantEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVariantsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<yggdrasil.messaging.VariantEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVariantsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<yggdrasil.messaging.ToggleStats> EndToggleStats(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.ToggleStats>(o);
  }
}


static public class ToggleStatsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*No*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Yes*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Variants*/, yggdrasil.messaging.VariantEntryVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
