// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VariantPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static VariantPayload GetRootAsVariantPayload(ByteBuffer _bb) { return GetRootAsVariantPayload(_bb, new VariantPayload()); }
  public static VariantPayload GetRootAsVariantPayload(ByteBuffer _bb, VariantPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VariantPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string PayloadType { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPayloadTypeBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPayloadTypeBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPayloadTypeArray() { return __p.__vector_as_array<byte>(4); }
  public string Value { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetValueBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetValueArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<yggdrasil.messaging.VariantPayload> CreateVariantPayload(FlatBufferBuilder builder,
      StringOffset payload_typeOffset = default(StringOffset),
      StringOffset valueOffset = default(StringOffset)) {
    builder.StartTable(2);
    VariantPayload.AddValue(builder, valueOffset);
    VariantPayload.AddPayloadType(builder, payload_typeOffset);
    return VariantPayload.EndVariantPayload(builder);
  }

  public static void StartVariantPayload(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPayloadType(FlatBufferBuilder builder, StringOffset payloadTypeOffset) { builder.AddOffset(0, payloadTypeOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, StringOffset valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.VariantPayload> EndVariantPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.VariantPayload>(o);
  }
}


static public class VariantPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*PayloadType*/, false)
      && verifier.VerifyString(tablePos, 6 /*Value*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
