// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace yggdrasil.messaging
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Variant : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Variant GetRootAsVariant(ByteBuffer _bb) { return GetRootAsVariant(_bb, new Variant()); }
  public static Variant GetRootAsVariant(ByteBuffer _bb, Variant obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Variant __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Enabled { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool ImpressionData { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool FeatureEnabled { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Name { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(10); }
  public yggdrasil.messaging.VariantPayload? Payload { get { int o = __p.__offset(12); return o != 0 ? (yggdrasil.messaging.VariantPayload?)(new yggdrasil.messaging.VariantPayload()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string Error { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetErrorBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetErrorArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<yggdrasil.messaging.Variant> CreateVariant(FlatBufferBuilder builder,
      bool enabled = false,
      bool impression_data = false,
      bool feature_enabled = false,
      StringOffset nameOffset = default(StringOffset),
      Offset<yggdrasil.messaging.VariantPayload> payloadOffset = default(Offset<yggdrasil.messaging.VariantPayload>),
      StringOffset errorOffset = default(StringOffset)) {
    builder.StartTable(6);
    Variant.AddError(builder, errorOffset);
    Variant.AddPayload(builder, payloadOffset);
    Variant.AddName(builder, nameOffset);
    Variant.AddFeatureEnabled(builder, feature_enabled);
    Variant.AddImpressionData(builder, impression_data);
    Variant.AddEnabled(builder, enabled);
    return Variant.EndVariant(builder);
  }

  public static void StartVariant(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddEnabled(FlatBufferBuilder builder, bool enabled) { builder.AddBool(0, enabled, false); }
  public static void AddImpressionData(FlatBufferBuilder builder, bool impressionData) { builder.AddBool(1, impressionData, false); }
  public static void AddFeatureEnabled(FlatBufferBuilder builder, bool featureEnabled) { builder.AddBool(2, featureEnabled, false); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(3, nameOffset.Value, 0); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<yggdrasil.messaging.VariantPayload> payloadOffset) { builder.AddOffset(4, payloadOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, StringOffset errorOffset) { builder.AddOffset(5, errorOffset.Value, 0); }
  public static Offset<yggdrasil.messaging.Variant> EndVariant(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<yggdrasil.messaging.Variant>(o);
  }
}


static public class VariantVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Enabled*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*ImpressionData*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*FeatureEnabled*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 10 /*Name*/, false)
      && verifier.VerifyTable(tablePos, 12 /*Payload*/, yggdrasil.messaging.VariantPayloadVerify.Verify, false)
      && verifier.VerifyString(tablePos, 14 /*Error*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
