name: Release-plz (Bindings)

on:
  push:
    branches: [ main ]
    paths:
      - 'yggdrasilffi/**'
      - 'release-plz.toml'
      - 'CHANGELOG.md'
      - '.github/workflows/release-plz.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-plz-pr:
    if: ${{ github.repository_owner == 'Unleash' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: App token
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.UNLEASH_BOT_APP_ID }}
          private-key: ${{ secrets.UNLEASH_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - uses: dtolnay/rust-toolchain@stable

      - name: release-plz (release-pr)
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}

  release-plz-release:
    if: ${{ github.repository_owner == 'Unleash' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: App token
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.UNLEASH_BOT_APP_ID }}
          private-key: ${{ secrets.UNLEASH_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - uses: dtolnay/rust-toolchain@stable

      - name: release-plz (release)
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}